### ISSUE TITLE
Travis not enabled

### ISSUE THREAD

**Issue by DePierre** [eik00d/CANToolz#91]
@eik00d It seems that you merged #86 but you didn't configure the github repository to actually use Travis. Not sure if that was intentional and you were going to do it soon or if you forgot.

So this issue is more of a reminder in case you forgot (see: https://travis-ci.org/eik00d/CANToolz)

Let me know if I'm missing something and sorry if I'm a pain :/

**Comment by eik00d** [comment]
@DePierre, thx! You are right... i just forgot. Will do this soon!

**Comment by eik00d** [comment]
Added
